FROM node:16

ENV TIME_ZONE=Europe/Paris

RUN echo $TIME_ZONE | tee /etc/timezone \
  && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update && apt-get install build-essential libssl-dev git -y

WORKDIR /usr/app

USER node

# Install global dependencies
RUN yarn global add nodemon
