---

# http://jsontoyaml.com

parser: "babel-eslint"

extends:
  - common

env:
  node: true
  es6: true

# Global scoped method and vars
globals:
  requireAll: false
  mongoose: false
  api : false
  log : false
  logInfo : false
  logWarn : false
  logError : false
  __NODE_ENV: false

parserOptions:
  # hack for strict rule
  sourceType: scrypt

rules:
  # # Strict Mode
  # # http://eslint.org/docs/rules/#strict-mode
  # strict:
  #   - 1
  #   - safe

  # Node.js and CommonJS
  # http://eslint.org/docs/rules/#nodejs-and-commonjs
  no-mixed-requires: 2
  no-new-require: 2
  no-path-concat: 2
  no-restricted-modules:
    - 2
    - sys
    - _linklist

  # Stylistic Issues
  # http://eslint.org/docs/rules/#stylistic-issues
  space-infix-ops: 2
  space-unary-ops: 2

  comma-dangle:
    - warn
    -
      arrays: always-multiline
      objects: always-multiline
      imports: only-multiline
      exports: only-multiline
      functions: ignore

  no-multi-spaces:
    - 2
    -
      exceptions:
        AssignmentExpression: true
        VariableDeclarator: true
        ImportDeclaration: true
        Property: true
